# Page settings
baseurl = "https://guillermo.guerreroibarra.com/"
languageCode = "en-us"
title = "Guillermo Guerrero Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-57386726-5"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

    # Meta
    description = "Guillermo Guerrero Resume"
    author = "Guillermo Guerrero"

    # Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

    # Sidebar sections

    # Profile section
    [params.profile]
        name = "Guillermo Guerrero"
        tagline = "Full Stack Developer"
        avatar = "portrait.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
          class = "email"
          icon = "fa-envelope"
          url = "mailto: guillermo@guerreroibarra.com"
          title = "guillermo@guerreroibarra.com"

        [[params.contact.list]]
          class = "linkedin"
          icon = "fa-linkedin"
          url = "https://es.linkedin.com/in/guillermoguerreroibarra"
          title = "linkedin.com/in/guillermo..."

        [[params.contact.list]]
          class = "github"
          icon = "fa-github"
          url = "https://github.com/ryanfox1985"
          title = "github.com/ryanfox1985"

        [[params.contact.list]]
          class = "twitter"
          icon = "fa-twitter"
          url = "https://twitter.com/ryan_fox85"
          title = "@ryan_fox85"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
          degree = "BSc in Computer Science"
          college = "Universitat Rovira i Virgili"
          dates = "2012"

        [[params.education.list]]
          degree = "Systems Engineering Technician"
          college = "Universitat Rovira i Virgili"
          dates = "2009"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
          language = "Spanish"
          level = "Native"

        [[params.languages.list]]
          language = "Catalan"
          level = "Native"

        [[params.languages.list]]
          language = "English"
          level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
          interest = "Travels"

        [[params.interests.list]]
          interest = "Tv shows"

        [[params.interests.list]]
          interest = "Retro games"

        [[params.interests.list]]
          interest = "Programming languages"

        [[params.interests.list]]
          interest = "Motorbikes"

        [[params.interests.list]]
          interest = "Running"

        [[params.interests.list]]
          interest = "Cooking"

    # Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """I was born in 1985 in Tarragona, Spain. Since I was a child I have always loved computers and games. So it's not surprising that I became a software engineer.<br /><br /> \
        I am passionate about new technologies and everything that moves around software. I enjoy making efficient clean code and improving my skills as a programmer. In the last years I have been mainly working with web services and applications.<br /><br /> \
        Whenever I have some time off I enjoy running, riding my motorbike, watching TV series and traveling to discover new places and cultures."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
          position = "Full-Stack Developer"
          dates = "Mar 2016 - Present"
          company = "Air Refund, Barcelona"
          details = """The IT department improves the platform according with the necessities from Customer Service, Account manager and traveler experience in our site.<br /><br /> \
          - Ruby on Rails, ReactJS, AngularJS, APIs.<br /> \
          - AWS, DevOps.<br /> \
          - Postgresql."""

        [[params.jobs.list]]
          position = "Cofunder"
          dates = "Oct 2014 - Present"
          company = "Devcows, Tarragona"
          details = """I worked as a freelance, I designed and created web services and mobile applications using a agile languages and frameworks like Ruby On Rails, Python, Django and Java.<br /><br /> \
          - Working with the latest technologies, Agile and Test-Driven Development.<br /> \
          - DevOps (Vagrant, Docker, CoreOS).<br /> \
          - AWS."""

        [[params.jobs.list]]
          position = "Software Engineer"
          dates = "Aug 2013 - Apr 2015 (1y 8m)"
          company = "Simpple, Tarragona"
          details = """Simpple is a small company. The company uses Bitbucket and Github as a source revision control also uses JIRA for tracking and planning the projects. Also Test-driven development and good methodologies for agile software development like Scrum.<br /><br /> \
          When I entered my position was a Cowboy Coding. I developed responsive web applications for company customers with Ruby on Rails using Bootstrap.<br /><br /> \
          - [Performance improvements in RoR](http://gguerrero1985.bitbucket.org/pdf/slides/performance_improvements/performance_improvements.pdf)<br /> \
          - [Getting started with Vagrant](http://gguerrero1985.bitbucket.org/pdf/slides/vagrant/vagrant.pdf)"""

        [[params.jobs.list]]
          position = "Software Engineer"
          dates = "Oct 2011 – Jul 2013 (1y 10m)"
          company = "AST Research Group, Tarragona"
          details = """I was assigned to the RealCloud project. The project consist in create a synchronization system "Personal Cloud" for small and medium business like Dropbox.<br /><br /> \
          Our Personal Cloud is composed by a system that we called Stacksync. It has a desktop client, a synchronization metadata system and Cloud Storage Service (Openstack Swift).<br /><br /> \
          For the desktop client we found an Open source project that synchronizes files (Syncany). We used this client and we fixed some bugs and we added some features for example connect to Openstack Swift.<br /><br /> \
          At the server part Openstack Swift we modify the ACL to share objects between clients."""

        [[params.jobs.list]]
          position = "Web developer"
          dates = "Feb 2011 – Apr 2011 (3m)"
          company = "Universitat Rovira i Virgili, Tarragona"
          details = """Collaboration with the Universitat Rovira i Virgili to build a web application in PHP and JQuery to create questionnaires, it has different type of answers: order by, select, open, etc. ASPACE can do the questionnaires to their centers with this web application."""


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
          title = "Hugrid"
          url = "https://github.com/aerohub/hugrid"
          tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
          title = "Simple FAQ Theme for Hugo"
          url = "https://github.com/aerohub/hugo-faq-theme"
          tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
          title = "Hugo Identity"
          url = "https://github.com/aerohub/hugo-identity-theme"
          tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
          title = "Orbit"
          url = "https://github.com/aerohub/hugo-orbit-theme"
          tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
          title = "Me"
          url = "https://github.com/aerohub/hugo-me-theme"
          tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
          skill = "Ruby on Rails"
          level = "100%"

        [[params.skills.list]]
          skill = "ReactJS"
          level = "100%"

        [[params.skills.list]]
          skill = "HTML5 & CSS"
          level = "100%"

        [[params.skills.list]]
          skill = "DevOps"
          level = "100%"

        [[params.skills.list]]
          skill = "Golang"
          level = "100%"

        [[params.skills.list]]
          skill = "Android"
          level = "80%"


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Guillermo Guerrero Ibarra"
